# Generated by Django 5.0.2 on 2024-03-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.IntegerField(choices=[(1, '無'), (2, '二年制專科學校及進修學校肄業學生'), (3, '三年制專科學校及進修學校肄業學生'), (4, '五年制專科學校及進修學校肄業學生'), (5, '大學學士班（不包括空中大學）肄業'), (6, '自學進修學力鑑定考試通過'), (7, '國家考試及格，持有及格證書'), (8, '技能檢定合格'), (9, '符合年滿22歲、高級中等學校畢（結）業或修滿規定修業年限，且已修畢畢業應修學分80學分以上'), (10, '持有高級中等學校畢業證書後，從事相關工作經驗五年以上'), (11, '曾於大學校院擔任專業技術人員、於專科學校或高級中等學校擔任專業及技術教師'), (12, '持國外或香港、澳門專科以上學校畢（肄）業學歷')], default=1),
            preserve_default=False,
        ),
    ]
